In [ ]:
'''1.	Write a Python Program to find sum of array?
2.	Write a Python Program to find largest element in an array?
3.	Write a Python Program for array rotation?
4.	Write a Python Program to Split the array and add the first part to the end?
5.	Write a Python Program to check if given array is Monotonic?
'''

In [6]:
'''1.	Write a Python Program to find sum of array?'''

def sum_of_array():
    import numpy as np
    num_of_ele_in_array = int(input('enter the number of elements in the array : '))
    lis=[]
    for i in range(1,num_of_ele_in_array+1):
        num = int(input(f'enter the {i}th element of array : '))
        lis.append(num)
    array=np.array(lis)
    
    sum_of_arr = np.sum(array)
    return (f'the sum of the array is = {sum_of_arr}')

In [7]:
sum_of_array()

enter the number of elements in the array : 4
enter the 1th element of array : 7
enter the 2th element of array : 8
enter the 3th element of array : 9
enter the 4th element of array : 7


'the sum of the array is = 31'

In [8]:
'''2.	Write a Python Program to find largest element in an array?'''

def max_ele_of_array():
    import numpy as np
    num_of_ele_in_array = int(input('enter the number of elements in the array : '))
    lis=[]
    for i in range(1,num_of_ele_in_array+1):
        num = int(input(f'enter the {i}th element of array : '))
        lis.append(num)
    array=np.array(lis)
    
    maximum = 0
    for j in lis:
        if j>maximum:
            maximum = j
    
    return maximum
        


In [9]:
max_ele_of_array()

enter the number of elements in the array : 4
enter the 1th element of array : 6
enter the 2th element of array : 7
enter the 3th element of array : 8
enter the 4th element of array : 9


9

In [35]:
'''3.	Write a Python Program for array rotation?'''

def rotation_of_array():
    import numpy as np
    num_of_ele_in_array = int(input('enter the number of elements in the array : '))
    lis=[]
    for i in range(1,num_of_ele_in_array+1):
        num = int(input(f'enter the {i}th element of array : '))
        lis.append(num)
    array=np.array(lis)
    
    popped_ele = None
    num = int(input('enter the number of times you want to rotate the array : '))
    while num>0:
        popped_ele = array[-1]
        array = array[:-1]
        array = np.insert(array,0,popped_ele)
        num = num - 1
    
    return array

In [36]:
rotation_of_array()

enter the number of elements in the array : 3
enter the 1th element of array : 1
enter the 2th element of array : 2
enter the 3th element of array : 3
enter the number of times you want to rotate the array : 1


array([3, 1, 2])

In [37]:
rotation_of_array()

enter the number of elements in the array : 3
enter the 1th element of array : 1
enter the 2th element of array : 2
enter the 3th element of array : 3
enter the number of times you want to rotate the array : 4


array([3, 1, 2])

In [43]:
'''4.	Write a Python Program to Split the array and add the first part to the end?'''

def splitting_of_array():
    import numpy as np
    num_of_ele_in_array = int(input('enter the number of elements in the array : '))
    lis=[]
    for i in range(1,num_of_ele_in_array+1):
        num = int(input(f'enter the {i}th element of array : '))
        lis.append(num)
    array=np.array(lis)
    
    pos = int(input("enter the position at which you want to split the array"))
    sliced_array = array[:pos]
    array = np.delete(array,slice(0,pos),axis =0)
    array = np.concatenate((array,sliced_array),axis=0)

In [62]:
'''5.	Write a Python Program to check if given array is Monotonic?'''

def check_monotonicity():
    import numpy as np
    num_of_ele_in_array = int(input('enter the number of elements in the array : '))
    lis=[]
    for i in range(1,num_of_ele_in_array+1):
        num = int(input(f'enter the {i}th element of array : '))
        lis.append(num)
    array=np.array(lis)
    
    increase , decrease = True , True
    
    for i in range(1,len(array)):
        if array[i]>array[i-1]:
            decrease = False
        elif array[i]<array[i-1]:
            increase = False
            break
            
            
    if increase==True:
        return ('monotonic increasing')
    elif decrease==True:
        return('monotonic decreasing')
    else:
        return ('not monotonic')

In [65]:
check_monotonicity()

enter the number of elements in the array : 3
enter the 1th element of array : 4
enter the 2th element of array : 7
enter the 3th element of array : 1


'not monotonic'

In [2]:
sum([8,9,7,8])

32

In [29]:
import numpy as np

In [30]:
s=[9,8,7,6,5]

In [31]:
s = np.array(s)

In [32]:
pop = np.delete(s,-1)

In [33]:
pop

array([9, 8, 7, 6])

In [34]:
s

array([9, 8, 7, 6, 5])

In [15]:
s[-2:]

[6, 5]

In [17]:
c=s.pop(-1)

In [18]:
c

6

In [19]:
s

[9, 8, 7]

In [20]:
s.insert(0,c)

In [21]:
s

[6, 9, 8, 7]

In [22]:
s = None

In [23]:
s = 0

In [24]:
s

0

In [ ]:
s = np.concatenate()

In [41]:
s

array([9, 8, 7, 6, 5])

In [39]:
si=s[:2+1]

In [40]:
si

array([9, 8, 7])